version: '3.9'
x-php: &php
  build: 
    context: .
    dockerfile: ./Dockerfile
  volumes:
    - "./:/app"
  networks:
    - internal
  environment:
    - APP_DEBUG=true
    - DB_CONNECTION=sqlite
    - DB_DATABASE=/app/database/database.sqlite
    - APP_KEY:base64:d1k91AgNcf1g7t/SVxBwE3u4NFK/I3vMH8Gyzl2Rvrs=

services:
  php:
    ports:
    - "8080:80"
    depends_on:
      - database
    <<: *php

  database:
    <<: *php
    command: php artisan migrate --force

  # postgres:
  #   image: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: app
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password

  #   networks:
  #     - internal

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - "./.pgadmin:/root/.pgadmin"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - ${PGADMIN_PORT:-5050}:80
  #   networks:
  #     - internal

  composer:
    image: composer:2.1.12
    working_dir: /comp
    volumes:
      - "./:/comp"
    command: composer install --ignore-platform-reqs

networks:
  internal:
    driver: bridge
